# Generated by Django 5.1.1 on 2024-09-28 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_reader_alter_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reader',
        ),
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
